### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by karkraeg** [DamascenoRafael/reminders-menubar#1]
Hi, do I have to build this or do you have an executable for download? Thanks!

**Comment by DamascenoRafael** [comment]
Hey, thanks for the question! 👋 
Currently it is necessary to build using Xcode (Product > Archive).
But my wish is to make some improvements and make it available through a download or through [brew](https://formulae.brew.sh/). 👨‍💻 
I will try to make some updates as soon as possible.

**Comment by iherman** [comment]
@DamascenoRafael I would really like to use this; will there be a release or something similar when you have it in brew?

**Comment by DamascenoRafael** [comment]
Hi, sorry for taking so long. I just released the first version 📦   🎉 

Please see the README file and let me know if something goes wrong.

I will keep this issue open for a few more days in case there is an installation problem.

I would love to receive any feedback or suggestions.
Also feel free to open a new issue if necessary.

**Comment by DamascenoRafael** [comment]
@karkraeg @iherman.
Closing this issue, since the first version was released last week 📦 

I hope you all enjoy it. 😄
