### ISSUE TITLE
Window reopens if one clicks at the very top of the icon

### ISSUE THREAD

**Issue by samcarter** [DamascenoRafael/reminders-menubar#101]
*(thank you very much for creating this very handy app, it is really convenient to have one's reminders available in the menu bar!)*

If the Reminders Menu Bar window is open and one clicks on the icon again, the window closes. That's expected behaviour and matches the behaviour of many other menu bar apps.

However there is a literal edge case: if one clicks at the very top of the icon, the window seems to close, but reopens immediately.

Here a short screen recording to demonstrate this behaviour:

https://user-images.githubusercontent.com/43832342/216600403-aee89424-d933-4fcd-8764-b3ee24e246c1.mp4

Reminders Menu Bar version: 1.13.0
macOS: 11.7.2

**Comment by DamascenoRafael** [comment]
Hi @samcarter. Thanks for your feedback :)
This really wasn't expected, but it's weird at the same time, hahaha.

Investigating the popover notifications (via NotificationCenter) and the moment the togglePopover() function is called I came to the following conclusions:

### When clicking to open the sequence of events is always the same:
1. togglePopover function
1. popover will show notification
1. popover did show notification

### When clicking in the center of the button to close the popover:
1. popover will close notification
1. popover did close notification

For some reason the togglePopover function is not even called in this case.

### When clicking in the top of the button to close the popover:
1. popover will close notification
1. popover did close notification
1. togglePopover function -- but at that moment the popover is already closed so the function opened it again

I couldn't figure out why this was happening. But I'm testing a way to work around this problem.

**Comment by samcarter** [comment]
@DamascenoRafael Thanks for having a look at this!

**Comment by DamascenoRafael** [comment]
@samcarter please let me know if the behavior is as expected in v1.16.0 📦

**Comment by samcarter** [comment]
@DamascenoRafael The new version works beautifully! Thanks a lot! 

(previously, I was switching back for some things to the mac app, but ever since you added the default date, I not once had to open the mac reminders app and could do everything just with your app, it is really handy!)

**Comment by samcarter** [comment]
@DamascenoRafael Just in case you get any reports: after updating to v1.16.0 I once had to re-do some setting, like allowing the app access to my calenders, moving it to previous position in my menu bar etc. I suspect that's because the app is now signed and mac essential threats it as different app than before. Everything works fine, just in case you get any related reports about this.

**Comment by DamascenoRafael** [comment]
@samcarter I'm glad that you are enjoying the app 🥳 
Please feel free to send new feedbacks or suggestions that may improve the app!!

About the need to redo some settings, thanks for letting me know. This could be due to the app's Bundle-id being renamed in v1.16.0. It should not occur in future versions.
