### ISSUE TITLE
Click to edit

### ISSUE THREAD

**Issue by jeremybagel** [DamascenoRafael/reminders-menubar#103]
I know this is kind of covered by the 3 dot contextual menu but the "normal" behaviour I'd expect would be to click to edit (I do this all the time) so find myself clicking at the reminder without being able to.  Probably an enhancement rather than a bug but it would be rather helpful.

**Comment by DamascenoRafael** [comment]
Hi @jeremybagel. Thanks for the feedback.
In Apple Reminders, text behaves like a textfield, but there are some issues with this approach.
I was thinking that when clicking on the reminder text the editing screen could open with the text in focus to be edited.

Let me know what you think about this solution:

https://user-images.githubusercontent.com/9842644/236690438-11516dfb-4fc9-477d-909c-615a7f89330f.mp4

**Comment by jeremybagel** [comment]
That works for me!  What are the issues with editing it in situ?

**Comment by jeremybagel** [comment]
If I may:

1. Seems reasonable.
2. Seems like a feat that can be easily overcome. 
3. The return or click out is an auto save. Multiple edits wouldn’t be an option since any single edit automatically commits.
