### ISSUE TITLE
Language Parsing?

### ISSUE THREAD

**Issue by TechRemarker** [DamascenoRafael/reminders-menubar#104]
Does this support language parsing? When typing "today buy milk" it doesn't appear to automatically add reminder for today. I use "today" or "in 3hrs" etc all the time so that it will automatically notify me, without having to manually select a specific day etc.

**Comment by DomizianoScarcelli** [comment]
Yes, it would be a very nice feature, and it's the only thing this app is currently missing. There has also been a discussion [here](https://github.com/DamascenoRafael/reminders-menubar/issues/17). A long time has passed since then, I really hope for this feature to come out soon!

**Comment by DomizianoScarcelli** [comment]
I wanted this feature so bad I decided to try to add it myself

**Comment by DamascenoRafael** [comment]
@TechRemarker version 1.14.0 is now available. It is now possible to specify the due date with natural language 🔤 📅 
Please let me know if you have any feedback or suggestions for improvement.

Thanks @DomizianoScarcelli for putting effort into this feature 🚀

**Comment by TechRemarker** [comment]
Thank you so much! Just tested, and partially worked, typed, "Testing tomorrow". It properly added the date for tomorrow, great, but it didn't remove the word tomorrow" in the actual reminder as it's suppose to after using the word for the meta. Tried "Clean in 5 days" and again it set the right date, but the reminder it saved was, "Clean in 5 days" rather than the correct, simply "Clean". Great start on adding the feature though, as imagine just a bug.

**Comment by DamascenoRafael** [comment]
Hi @TechRemarker.

To work this way you need to check the option shown in the image below:
<img width="710" alt="Screenshot 2023-03-06 at 20 18 57" src="https://user-images.githubusercontent.com/9842644/223278831-69480d3d-1b93-4e04-93d3-0857d7c2e3ae.png">

Once this option is checked the date will be removed from the title for reminders created thereafter.

**Comment by TechRemarker** [comment]
Thank you! For some reason that wasn't enabled by default. Checking it resolves the issue. Would just presumably want to make sure that's the default since that's the default for all other to do apps that I can think of such as Apple Reminders, Apple Calendar, Fantastical, Todoist, Things, etc. I believe in all those apps to have it parse without removing you use, quotes around it, such as "Pickup kids tomorrow". Ideally quotes like that would work as well here, but in the meantime looks like one can simply enable that remove parsed option for those times one wants to add that exact text. Thank you!
