### ISSUE TITLE
[Natural Language Processing] Writing "Today" parses the date in the following year

### ISSUE THREAD

**Issue by DomizianoScarcelli** [DamascenoRafael/reminders-menubar#108]
As the title says, and I think this is my error in adding the feature, if we insert a sentence like:

"Do something today", will parse the date as the same day for the following year. I don't know if this happened before and why I never caught it during development, but I think the particular case of "Today" parsing should avoid the time adjustment.

**Comment by DamascenoRafael** [comment]
Hey @DomizianoScarcelli thanks for your feedback. 
I made some changes to the feature, trying to keep the same functionality. But I believe I missed something. From my observations this seems be happening for the word "today" only after 11pm. But anyway it's a bug that needs to be fixed.
I have already found the bug and I will fix it.
