### ISSUE TITLE
Add missing translations to Localizable.strings

### ISSUE THREAD

**Issue by DamascenoRafael** [DamascenoRafael/reminders-menubar#109]
Hi folks. With the addition of some new features, some translations were missing or outdated.

- [x] German 🇩🇪 
- [x] Spanish (Latin America) 🇲🇽 
- [x] Italian 🇮🇹 
- [x] Japanese 🇯🇵 
- [x] Dutch 🇳🇱
- [x] Polish 🇵🇱 
- [x] Chinese (Simplified) 🇨🇳 

The translations that need to be fixed are for the locations indicated in the images below.
Depending on the language all are needed or just some of them.

Sorry to bother, I'm tagging here the people who have already helped with the translations ❤️
But any contributor is welcome!! 🧑‍💻 

<img width="630" alt="Screenshot 2023-03-03 at 00 08 41" src="https://user-images.githubusercontent.com/9842644/222622465-dbcf9bac-a07b-4011-8526-9890cd10265e.png">

<img width="474" alt="Screenshot 2023-03-03 at 00 09 26" src="https://user-images.githubusercontent.com/9842644/222622497-2354ac31-fb70-4e8d-a932-c86f87405751.png">

---

**German 🇩🇪** 

@Somberland

https://github.com/DamascenoRafael/reminders-menubar/blob/0b8999222da75481279f1206bcf4628baaea21e5/reminders-menu-bar/Resources/de.lproj/Localizable.strings#L5-L6

https://github.com/DamascenoRafael/reminders-menubar/blob/0b8999222da75481279f1206bcf4628baaea21e5/reminders-menu-bar/Resources/de.lproj/Localizable.strings#L38-L39

---

**Spanish 🇲🇽** 

@zydeico

https://github.com/DamascenoRafael/reminders-menubar/blob/0b8999222da75481279f1206bcf4628baaea21e5/reminders-menu-bar/Resources/es-419.lproj/Localizable.strings#L5-L6

https://github.com/DamascenoRafael/reminders-menubar/blob/0b8999222da75481279f1206bcf4628baaea21e5/reminders-menu-bar/Resources/es-419.lproj/Localizable.strings#L38-L39

---

**Italian 🇮🇹** 

@DomizianoScarcelli @Angelk90

https://github.com/DamascenoRafael/reminders-menubar/blob/0b8999222da75481279f1206bcf4628baaea21e5/reminders-menu-bar/Resources/it.lproj/Localizable.strings#L5-L6

---

**Japanese 🇯🇵** 

@shos-03

https://github.com/DamascenoRafael/reminders-menubar/blob/0b8999222da75481279f1206bcf4628baaea21e5/reminders-menu-bar/Resources/ja.lproj/Localizable.strings#L5-L6

https://github.com/DamascenoRafael/reminders-menubar/blob/0b8999222da75481279f1206bcf4628baaea21e5/reminders-menu-bar/Resources/ja.lproj/Localizable.strings#L38-L39

---

**Dutch 🇳🇱**

@0xWDG

https://github.com/DamascenoRafael/reminders-menubar/blob/0b8999222da75481279f1206bcf4628baaea21e5/reminders-menu-bar/Resources/nl.lproj/Localizable.strings#L5-L6

https://github.com/DamascenoRafael/reminders-menubar/blob/0b8999222da75481279f1206bcf4628baaea21e5/reminders-menu-bar/Resources/nl.lproj/Localizable.strings#L38-L39

---

**Polish 🇵🇱** 

@emce

https://github.com/DamascenoRafael/reminders-menubar/blob/0b8999222da75481279f1206bcf4628baaea21e5/reminders-menu-bar/Resources/pl.lproj/Localizable.strings#L5-L6

---

**Chinese 🇨🇳** 

@receyuki

https://github.com/DamascenoRafael/reminders-menubar/blob/0b8999222da75481279f1206bcf4628baaea21e5/reminders-menu-bar/Resources/zh-Hans.lproj/Localizable.strings#L5-L6

https://github.com/DamascenoRafael/reminders-menubar/blob/0b8999222da75481279f1206bcf4628baaea21e5/reminders-menu-bar/Resources/zh-Hans.lproj/Localizable.strings#L38-L39

**Comment by Piaziker** [comment]
[newReminderTextFielPlaceholder.txt](https://github.com/DamascenoRafael/reminders-menubar/files/10896145/newReminderTextFielPlaceholder.txt)
Hello,
Here's a first pass at a French translation. This little app is a gem, thanks so much for creating it!

**Comment by DamascenoRafael** [comment]
Thanks @Piaziker. I'm glad you like the app 🥳 

Would you have Xcode to follow the instructions that are in the [README > Languages > Click here to learn how to add new languages 🌐](https://github.com/DamascenoRafael/reminders-menubar#languages) ? If possible open a Pull Request with the changes from these instructions.

**Comment by DamascenoRafael** [comment]
Tagging here in case someone has missed it.

The translations that still need to be updated are:
- Italian 🇮🇹 - @DomizianoScarcelli @Angelk90
- Japanese 🇯🇵 - @shos-03
- Dutch 🇳🇱 - @0xWDG
