### ISSUE TITLE
Menubar icon customisation

### ISSUE THREAD

**Issue by gferreroferri** [DamascenoRafael/reminders-menubar#11]
It would be great to be able to change the menubar icon. At least I would like to see some options, like SFSymbol list.bullet, list.bullet.rectangle, etc.

**Comment by DamascenoRafael** [comment]
Hey @gferreroferri, thanks for the feedback!

I'm also not a big fan of the current icon in the menu bar. I was thinking of changing the default icon to one of your suggestions.

Below is a comparison between the current icon and its suggestions:

<img width="676" alt="Screen Shot 2021-02-27 at 11 10 26" src="https://user-images.githubusercontent.com/9842644/109430333-91758c80-79df-11eb-90b2-14b6293241ec.png">

I think the "list.bullet" is the most interesting, what do you think?

Also, by changing the default icon do you think there is still a need for an option to customize the icon among other options?

**Comment by gferreroferri** [comment]
I think the list.bullet looks great. I would be happy only with that one :)
