### ISSUE TITLE
Feature Request: Select reminder list via text (temporarily override list where it will be saved)

### ISSUE THREAD

**Issue by mykeatkinson** [DamascenoRafael/reminders-menubar#119]
It would be great if there was a way to use text input to temporarily override the list a new reminder is being added to without changing the list in the menu with the mouse. This would allow one list to be used as the main "inbox" for most new items, but allow for users to place a new item directly into a specifc list if they know where they want it to go without changing the list selection back and forth or sorting/moving later.

For example, Fantastical allows a new calendar or reminder to be assigned to a specific list of calendar when the user types "/" and then autocompletes after the types the first letters of the list or calendar.
![image](https://user-images.githubusercontent.com/47463958/224127057-5f4841b2-c4ea-445c-9810-b0f5984928cc.jpeg)

**Comment by DamascenoRafael** [comment]
Thanks for your feedback @mykeatkinson! This looks like a nice addition to the app.

In Fantastical, right after selecting the suggested list, does it remove the `/list` from the title?
We need to think about how this will be designed for the app. If you can add a video of how it works on Fantastical, that might be a hint on how we can do it.

**Comment by mykeatkinson** [comment]
Here's a video of it working on Fantastical:

https://github.com/DamascenoRafael/reminders-menubar/assets/47463958/8bb2e83b-82ce-48c4-8637-2b1963ef775c

**Comment by DamascenoRafael** [comment]
It will be available in the next version :)
Is code completed, just a few tests and validations now.

**Comment by mykeatkinson** [comment]
@DamascenoRafael I just tested it out a bit and it seems to be working great! Thanks so much!

**Comment by mykeatkinson** [comment]
@DamascenoRafael A quick ping to reiterate how much I appreciate this addition to the app. It's really helped me and it's working super well. Thanks for developing this fantastic little app that helps me daily. 🙏

**Comment by DamascenoRafael** [comment]
Thanks @mykeatkinson!!! It means a lot to know that the app helps you daily 🥳 
Let me know if you have any other ideas to make the app even better.
