### ISSUE TITLE
1.14.1 release downloads version 1.14.0

### ISSUE THREAD

**Issue by Jack-Bristow** [DamascenoRafael/reminders-menubar#123]
The file contained in the latest release still has the version number 1.14.0.
<img width="718" alt="image" src="https://user-images.githubusercontent.com/6740305/224747054-6fb0ba7e-b4b2-4098-a14f-340e5db89762.png">

**Comment by DamascenoRafael** [comment]
Hi @Jack-Bristow, did you download the zip directly from GitHub? Can you please recheck?
I downloaded it, unzipped it and the version is the expected 1.14.1.

**Comment by Jack-Bristow** [comment]
Huh that's strange, Alfred says the app version is 1.14.0 even though the plist states version 1.14.1, double checked through Finder and the correct version is stated.
