### ISSUE TITLE
Clearing items is really slow (again)

### ISSUE THREAD

**Issue by desilinguist** [DamascenoRafael/reminders-menubar#125]
Thanks for creating a fantastic app! I have been using it every day. One thing I've noticed with the latest release (the apple developer signed one) is that app is really slow (and sometimes even beachballs) when checking off items. This used to be the case in really old releases but then more recent ones fixed the issue. Not sure why there's a regression with this release. JFYI.

**Comment by DamascenoRafael** [comment]
Hi @desilinguist thanks for your feedback.
In release v1.16.0 we were re-instantiating a class where it wasn't needed.
Can you please check if this behavior has improved in version 1.16.1?

**Comment by desilinguist** [comment]
Hi @DamascenoRafael, I tried 1.16.1 and it still seems kind of slow compared to a few release ago when it seemed to be lightning fast.

**Comment by DamascenoRafael** [comment]
Thanks for checking @desilinguist. I'll try to investigate some optimizations that can be done in this regard.

**Comment by DamascenoRafael** [comment]
@desilinguist can you please check the v1.17.0 release? 📦 
I refactored how the reminder list was created, resulting in improved memory usage and faster loading times for large lists.
Hopefully this resolves the behavior you are experiencing.

**Comment by desilinguist** [comment]
Hi @DamascenoRafael I saw some improvements but still saw beach balls in other cases. Just to be sure, I completely uninstalled the app (using AppCleaner) and re-ran it. Still the same. I am attaching a screen capture that shows how slow it is for me.


https://user-images.githubusercontent.com/161680/232354279-36c7bb6e-db2b-4879-ae92-c318b4f59b13.mp4

**Comment by DamascenoRafael** [comment]
Hey @desilinguist, I made some improvements in version 1.19.0, removing some methods from the View layer (which could cause the slowdowns you reported). Can you please test and let me know the results?

Also can you give me an overview of how many reminders you have? I tried adding more reminders to experience a slowdown, but I couldn't reproduce the behavior you showed in the video.

Thanks for helping me to investigate this behavior.

**Comment by desilinguist** [comment]
Hi @DamascenoRafael! Thanks for tagging me and letting me know about the update. I just installed it and so far I am seeing the same behavior as in the video.

I don't have a lot of reminders but I do have at least 5-6 daily recurring reminders and a few others that are recurring weekly/monthly. 

If you need anything more specific, I am happy to provide. Please let me know.

**Comment by DamascenoRafael** [comment]
Hi @desilinguist, can you open Apple Reminders and check the number of reminders in "All" and "Completed"?
At the moment I have 115 on "All" and around 500 on "Completed".
I'm still looking for other small improvements, but I'm still not sure where the botleneck is exactly.

<img width="284" alt="image" src="https://github.com/DamascenoRafael/reminders-menubar/assets/9842644/e4987092-208e-4c2b-a821-86c09e560622">

**Comment by desilinguist** [comment]
Aha! That was the issue. I had ~12000 completed reminders! Cleared those out and things seem to be much snappier! Thanks for pointing that out @DamascenoRafael !

**Comment by DamascenoRafael** [comment]
@desilinguist I'm glad to hear that things got more responsive!! 🚀 
In any case, I'll keep working on some optimizations so the app stays fast even with lots of items.

Please feel free to open new issues if needed 😄
