### ISSUE TITLE
Add smart lists (Today, Scheduled, etc.)

### ISSUE THREAD

**Issue by adamlurie** [DamascenoRafael/reminders-menubar#13]
This app is great! Any chance that the "smart lists" (i.e. Today, Scheduled, etc.) could be displayed?

**Comment by DamascenoRafael** [comment]
Sounds like a great idea! Thank you for your feedback! 🎉 

We discussed something like this in #12 and I'm working on it.

As soon as I can, I'll put a picture here of how it looks so far.

**Comment by DamascenoRafael** [comment]
Hey @adamlurie, I'm closing this issue since this type of list was added in the last commit 🎉 

Some discussions should continue at #12, it would be nice to hear your opinions too 😄
