### ISSUE TITLE
Feature request: The default priority for all reminders be set to high

### ISSUE THREAD

**Issue by pearresearch** [DamascenoRafael/reminders-menubar#135]
<img width="193" alt="image" src="https://user-images.githubusercontent.com/110237207/235003082-a8f95e13-1e42-41bb-bedb-0cf3aa4bf93a.png">

Alternatively, even an option to change that from here directly would work. Thank you for the app!

**Comment by DamascenoRafael** [comment]
Thanks for the feedback @pearresearch. I'm adding an option to change priority through this menu.
