### ISSUE TITLE
Ventura Beta update, brew upgrade error 

### ISSUE THREAD

**Issue by lauragayle** [DamascenoRafael/reminders-menubar#139]
Greetings-
copied/pasted from Terminal window. If this is not the correct method to report, please let me know. I do understand the risks of using beta software. 
thanks!
****

==> Upgrading reminders-menubar
==> Downloading https://github.com/DamascenoRafael/reminders-menubar/releases/do
==> Downloading from https://objects.githubusercontent.com/github-production-rel
######################################################################### 100.0%
==> Backing App 'Reminders MenuBar.app' up to '/usr/local/Caskroom/reminders-men
==> Removing App '/Applications/Reminders MenuBar.app'
==> Moving App 'Reminders MenuBar.app' to '/Applications/Reminders MenuBar.app'
==> Purging files for version 1.18.0 of Cask reminders-menubar
==> Purging files for version 1.18.0 of Cask reminders-menubar
Warning: Reverting upgrade for Cask reminders-menubar
==> Purging files for version 1.17.0 of Cask reminders-menubar
Error: reminders-menubar: undefined method `artifacts' for #<Hash:0x00007fd76a156730>
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cask/upgrade.rb:127:in `upgrade_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:253:in `upgrade_outdated_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:137:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'

**Comment by DamascenoRafael** [comment]
Hi @lauragayle, thanks for reporting.
I'm not sure if it could be an issue with the app or with brew.

Could you try running the command below and maybe closing and reopening the terminal before trying to update the app?

```bash
brew update-reset && brew update && brew cleanup
```

**Comment by lauragayle** [comment]
Sure. This is what came across (I've put in XXX for the name of my local drive/directory):

==> Fetching /usr/local/Homebrew...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 7 (delta 3), reused 6 (delta 3), pack-reused 0
Unpacking objects: 100% (7/7), 6.54 KiB | 744.00 KiB/s, done.
From https://github.com/Homebrew/brew
   aa450ea82..177305659  master     -> origin/master

==> Resetting /usr/local/Homebrew...
branch 'master' set up to track 'origin/master'.
Switched to and reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/damascenorafael/homebrew-tap...
From https://github.com/damascenorafael/homebrew-tap
 * [new branch]      migrate-to-homebrew -> origin/migrate-to-homebrew

==> Resetting /usr/local/Homebrew/Library/Taps/damascenorafael/homebrew-tap...
branch 'main' set up to track 'origin/main'.
Reset branch 'main'
Your branch is up to date with 'origin/main'.

Already up-to-date.
Removing: /Users/XXX/Library/Caches/Homebrew/Cask/reminders-menubar--1.17.0.zip... (1MB)
Removing: /Users/XXX/Library/Logs/Homebrew/tesseract... (64B)
Removing: /Users/XXX/Library/Logs/Homebrew/zstd... (64B)
Pruned 0 symbolic links and 2 directories from /usr/local
==> This operation has freed approximately 1MB of disk space.

**Comment by lauragayle** [comment]
Reminders MenuBar was still appearing in my applications list; I tried to open it and got a damaged something message. Have removed it for now. Just FYI. Happy to try again.

**Comment by DamascenoRafael** [comment]
@lauragayle After removing it, when you try to install it again do you get the same message that was appearing initially?

**Comment by lauragayle** [comment]
No, seems to have installed correctly and is working. Thank you!

**Comment by DamascenoRafael** [comment]
Great to hear this!
I will close this issue then. Please feel free to open another issue if you find any other problems.
