### ISSUE TITLE
Show total number of reminders due today in menubar?

### ISSUE THREAD

**Issue by deathlyfrantic** [DamascenoRafael/reminders-menubar#14]
Hey there, this is a really cool app! Thanks for creating and sharing it!

Any chance there could be an option to show the number of reminders due today in the menubar? Todoist does this and I find it super helpful for knowing whether I still have something I need to do on a given day. Example:

<img width="49" alt="Screen Shot 2021-04-07 at 1 48 37 PM" src="https://user-images.githubusercontent.com/7629614/113911426-f58e2c00-97a7-11eb-94a5-ed5b286fd23a.png">

It's really easy for me to glance up and see that there's still something (1 task) I need to do today. (If there are none then it doesn't show a number at all.)

Thanks for the consideration!

**Comment by DamascenoRafael** [comment]
Hello @deathlyfrantic, thanks for the feedback!

I think it is an excellent idea!! I hadn't thought about it yet.

I will try to figure out the best way to do this and keep the number of tasks up to date.
As soon as I make progress on this I will let you know.

**Comment by DamascenoRafael** [comment]
@deathlyfrantic I will try to release a new version with this feature this week 😄

**Comment by DamascenoRafael** [comment]
Some screenshots:

<img width="412" alt="Screen Shot 2021-04-27 at 01 13 42" src="https://user-images.githubusercontent.com/9842644/116184370-ff93b280-a6f5-11eb-9ac5-0bc0cf23cdc6.png">

<img width="485" alt="Screen Shot 2021-04-27 at 01 13 53" src="https://user-images.githubusercontent.com/9842644/116184376-01f60c80-a6f6-11eb-94bd-1dc6c45dd7e7.png">

**Comment by deathlyfrantic** [comment]
This looks great! Thanks for doing it!

**Comment by DamascenoRafael** [comment]
@deathlyfrantic version 1.5.0 has just been released 📦

**Comment by deathlyfrantic** [comment]
This is amazing! Thank you!
