### ISSUE TITLE
Feature: Allow date parser to detect time when auto suggest today is enabled

### ISSUE THREAD

**Issue by DamascenoRafael** [DamascenoRafael/reminders-menubar#140]
At the moment, when some date/time has been defined by the user the detection of the date parser is stopped. This includes when today's date is suggested because the auto suggest today as date option is enabled.

It would be nice if the date parser could suggest time-only to add when only the date has been defined outside the parser.

As we are using Apple's NSDataDetector API this is relatively complicated and has different edge cases. The API does not provide for example if time-only was detected or if it was a date+time (when time-only is detected this is returned as the current day at the detected time).

This feature should not overwrite dates that were manually entered.
This feature was first discussed in #136

**Comment by yoghurtdewdew** [comment]
<img width="282" alt="image" src="https://github.com/DamascenoRafael/reminders-menubar/assets/63794438/18484c55-1f4d-441e-b8ee-40482404d4ce">

I found the same problem:
Unable to recognize date when opening both Suggested Today and Recognized Date simultaneously

**Comment by DamascenoRafael** [comment]
@yoghurtdewdew I have some insights on how I'm going to fix this.

**Comment by DamascenoRafael** [comment]
Working on this, it will be available in the next version.
