### ISSUE TITLE
Feature Request: Select task list via text/natural language processing

### ISSUE THREAD

**Issue by liam-k** [DamascenoRafael/reminders-menubar#147]
Hi! First of all, thank you for this amazing app. Love using it every time and it makes interacting with my reminders so much more sleek. 

However I do have a feature request which would make it even sleeker – please implement selecting a project/task list by just typing a symbol and the project name, like just writing "@ Shopping List" would switch the current list to the shopping list. (A similar thing with #tags would be great too btw).

Alternatively, selecting a list by pressing a shortcut (like Cmd+1, Cmd+2, Cmd+3 or similar) could also make things quicker. I switch a lot between lists so this would save me a ton of clicks over a day.

**Comment by DamascenoRafael** [comment]
Hey @liam-k, thanks for the feedback. This is definitely on my roadmap!! 🚀 

This is a duplicate issue of #119. Can you please add your comments there?
That way we can focus the discussion in one place. I would rename the other issue to be more clear about what it is.

**Comment by liam-k** [comment]
Oops, sorry about that, I indeed didn’t recognize the similarity by the title.

**Comment by DamascenoRafael** [comment]
No worries, anyway it's important to see that the feature is important to more people.

**Comment by DamascenoRafael** [comment]
Hey @liam-k, just to let you know that [v1.20.0](https://github.com/DamascenoRafael/reminders-menubar/releases/tag/v1.20.0) was released with this feature.
You can now use `/<list>` or `@<list>` to save a reminder to a specific list.
```
Study for math test /study
```
```
Study for math test @study
```

**Comment by liam-k** [comment]
Awesome, thank you so much!! Works really well :)
