### ISSUE TITLE
The normal authorization process cannot be completed.

### ISSUE THREAD

**Issue by Shawn-Jones-7** [DamascenoRafael/reminders-menubar#149]
[上传225.pict...]()
Occurred in version 13.4
请告诉我如何处理它。谢谢您。

**Comment by DamascenoRafael** [comment]
Hey @Shawn-Jones-7, can you please provide more information?
I'm also using macOS 13.4 and I have no problem authorizing the use of Reminders.
Do you have a screenshot of what happens or can you let me know if the app crashes?

Anyway, you can open System Settings > Privacy & Security > Reminders, and authorize the app.
<img width="827" alt="image" src="https://github.com/DamascenoRafael/reminders-menubar/assets/9842644/39c08e12-10e4-4ae2-b930-d47c51a267ca">

**Comment by DamascenoRafael** [comment]
@Shawn-Jones-7, can you please add more information to this?

**Comment by Shawn-Jones-7** [comment]
[屏幕录制2023-06-30 11.40.14.mov.zip](https://github.com/DamascenoRafael/reminders-menubar/files/11913339/2023-06-30.11.40.14.mov.zip)
I have recorded the operation video. I hope it can help you.

**Comment by DamascenoRafael** [comment]
@Shawn-Jones-7 can you please test version v1.20.0?

If the app does not request authorization and the window saying that the app was not authorized appears, please note if there is a question mark button as in the image below. If there is an error message when requesting authorization in v1.20.0, this button should be available and when you click it you should have more information about why it is failing.

<img width="372" alt="Screenshot 2023-07-02 at 23 16 14" src="https://github.com/DamascenoRafael/reminders-menubar/assets/9842644/69df3b8a-17c0-4120-9947-55bffcad31b4">

Please let me know if you managed to use the app in this new version.

**Comment by DamascenoRafael** [comment]
@Shawn-Jones-7 waiting for your response to understand if this issue has been resolved.

**Comment by DamascenoRafael** [comment]
Closing this as there was no response. It can be reopened if the issue still persists.

**Comment by DamascenoRafael** [comment]
Possibly related to #159 or #25.
