### ISSUE TITLE
Contributing for Translations

### ISSUE THREAD

**Issue by filippo-bernardi** [DamascenoRafael/reminders-menubar#15]
Hi!
First of all, I would like to thank you for this fantastic app!
I would like to help this project by translating the app in Italian.
How can I contribute?

**Comment by DamascenoRafael** [comment]
Hey @filippo-bernardi, thanks for your comment!
And thank you for offering to contribute to this project! 🎉 

It would be great to see Italian 🇮🇹  and many other languages available 🚀 

The project is not yet configured to use LocalizedStrings.
So the first step would be to organize the project to use Strings Files;
then it would be necessary to obtain all the strings in English from a file of this type. 
From then on it will be possible to create a new Strings File based on the English one for each language.

If you want I can help with this initial setup 😃

**Comment by filippo-bernardi** [comment]
That would be great!
I'm new to this so your help will be very appreciated 😄

**Comment by Angelk90** [comment]
@filippo-bernardi , @DamascenoRafael : Are there any news?

**Comment by DamascenoRafael** [comment]
@filippo-bernardi, @Angelk90 Sorry for taking so long.
I just separated the app strings into a Localizable.strings file!

To add a new location just follow the steps below:
- Open the Xcode project
- In Project navigator select the project reminders-menu-bar (first item)
- On the screen on the right, select again the reminders-menu-bar project (not the target)
- In the "Info" tab under "Localizations" select the "+" button and choose the new location to add
- In the list of "Resource files" keep selected only the Localizable.strings file
- Then a file version for the new location will be created and can be edited with the translations

**Comment by Angelk90** [comment]
@DamascenoRafael : I think it's useful to be able to make the user choose whether to use their own language that PC or the original.

**Comment by DamascenoRafael** [comment]
It will definitely be interesting. I might need the translation of some other strings, but I let you know.

**Comment by DamascenoRafael** [comment]
@Angelk90 I added the option to change the preferred language 👍 
Could you update the translation values in Localizable.strings and InfoPlist.strings to Italian?

**Comment by Angelk90** [comment]
@DamascenoRafael : Done.
