### ISSUE TITLE
Support Reminder Groupings

### ISSUE THREAD

**Issue by skoonin** [DamascenoRafael/reminders-menubar#155]
Just installed this app to try it out and it's great. It almost solved my problem with one snag.  I have my reminders grouped via indentations. It's a newer feature in the app. 

For example in my reminders (all) list I see: 
- **To Do**
  - Task 1
  - Task 2

In your menubar app I see : 
- To Do
- Task 1
- Task 2

Thanks for all your work on this, if I knew swift I would help!

**Comment by DamascenoRafael** [comment]
@skoonin thanks for you feedback. This is something I wish I had made available in the app for a while. In fact, Apple does not provide access to this information through the API, but there are workarounds to access information that the API does not provide. I'm currently working on this, and I believe I can make it available in the next version of Reminders MenuBar.

Here's a sneak peak of it working:
<img width="775" alt="Screenshot 2023-09-24 at 22 39 34" src="https://github.com/DamascenoRafael/reminders-menubar/assets/9842644/b23c70df-65f0-43ad-a1ab-965adceded57">

There is already an older issue about this feature where I will post updates.
We can keep the discussion there: https://github.com/DamascenoRafael/reminders-menubar/issues/36 [Handle subtasks and subgroups (nested lists) in a nicer way](https://github.com/DamascenoRafael/reminders-menubar/issues/36).

I will mark this issue as a duplicate and close it. Please post any other concerns about this feature in #36.
Feel free to open other issues if necessary.
