### ISSUE TITLE
Auto suggest today is sometimes a bit ahead of times

### ISSUE THREAD

**Issue by samcarter** [DamascenoRafael/reminders-menubar#157]
I love the "Auto suggest today as date" option and use it for all my reminders.

<img width="240" alt="Screenshot 2023-08-09 at 23 13 18" src="https://github.com/DamascenoRafael/reminders-menubar/assets/43832342/05ef4bd8-a017-4664-8942-c91d410a4569">

It works perfectly fine for 95.8 % of the time, but if try to add a new reminder after 11 pm, then it suggests tomorrow instead of today:

<img width="283" alt="Screenshot 2023-08-09 at 23 07 58" src="https://github.com/DamascenoRafael/reminders-menubar/assets/43832342/d7b40ee6-4d7b-4122-9c3f-32294eb26424">

Environment:

- Reminders MenuBar version 1.20.00
- my time zone: Central European Summer Time ( = UTC/GMT +2 hours)

**Comment by DamascenoRafael** [comment]
Hey @samcarter, thanks for the feedback.
I know what's causing this. If "auto suggest today" was not checked, the suggested date if you entered it manually would be the current moment rounded to the next hour (without minutes). So, if it was 8/9 at 11:02pm, the suggested date would be 8/10 at 12:00am (midnight).
I will fix this soon.

**Comment by samcarter** [comment]
@DamascenoRafael  Thanks for your explanation! My first thought was something about time zones, but neither the 1 hour nor the direction made sense, so very much appreciated that you could explain this riddle.

**Comment by samcarter** [comment]
@DamascenoRafael  Thank you very much for the fix!
