### ISSUE TITLE
Feature Request: Multiple iCloud Accounts

### ISSUE THREAD

**Issue by kaushikg94** [DamascenoRafael/reminders-menubar#160]
Is it possible to have it set up where you can use multiple iCloud accounts?

**Comment by DamascenoRafael** [comment]
Hey @kaushikg94, the application reads the Apple Reminders data. So if you manage to use multiple accounts within Apple Reminders this data should be available in the app. Does this help your request?

https://support.apple.com/guide/reminders/use-reminders-from-your-internet-accounts-remnd5faf3ad/mac

**Comment by DamascenoRafael** [comment]
@kaushikg94 were you able to add a new account to your Apple Reminders?

**Comment by DamascenoRafael** [comment]
Closing this as there was no response.
