### ISSUE TITLE
Cursor is leaving input field to the right while typing long texts

### ISSUE THREAD

**Issue by od-gk** [DamascenoRafael/reminders-menubar#161]
The current cursor position should stay visible in the input field while typing. currently I am able to type about 10 to 15 more characters until the entered texts starts scrolling to the left. Thx! I am on macOS Ventura 13.5.2 (22G91).

https://github.com/DamascenoRafael/reminders-menubar/assets/103491503/c8f10665-5688-4822-8cf3-a7792a7cf82d

**Comment by DamascenoRafael** [comment]
@od-gk on my machine the cursor follows the text. I believe this may be due to the macOS version. I'm using macOS Ventura 13.4, could you tell me the version of macOS you're using?

**Comment by od-gk** [comment]
Hi Rafael,

Thank you for following up on this issue. I am on macOS Ventura 13.5.2 on a M1 MacBook Pro 13.

Kind regards, Oliver

On 18. Sep 2023, at 05:22, Rafael Damasceno ***@***.***> wrote:



@od-gk<https://github.com/od-gk> on my machine the cursor follows the text. I believe this may be due to the macOS version. I'm using macOS Ventura 13.4, could you tell me the version of macOS you're using?

**Comment by DamascenoRafael** [comment]
Hey @od-gk, thanks for the info.
I updated my mac to 13.5.2, and I'm still not experiencing the behavior you shared.
Can you confirm that you are using the latest version of the app (1.20.0)?

https://github.com/DamascenoRafael/reminders-menubar/assets/9842644/1c46ff31-fefa-440b-9124-ea618490d7d8

Let me know if I'm missing something here.
I will continue researching what could be happening.

**Comment by od-gk** [comment]
HI Rafael,

Yes, I can confirm. I am on the latest version 1.20.0. Interestingly, after restarting my MacBook the cursor stays in the input field and text is moving to the left while typing as expected.  I did not change the configuration and neither updated Reminder MenuBar nor applied any OS update in between. I will keep an eye on it, to have a chance to figure out if it can be reproduced.

Best, Oliver

[Screenshot 2023-09-20 at 09.50.51.png]

On 20. Sep 2023, at 06:51, Rafael Damasceno ***@***.***> wrote:



Hey @od-gk<https://github.com/od-gk>, thanks for the info.
I updated my mac to 13.5.2, and I'm still not experiencing the behavior you shared.
Can you confirm that you are using the latest version of the app (1.20.0)?

https://github.com/DamascenoRafael/reminders-menubar/assets/9842644/1c46ff31-fefa-440b-9124-ea618490d7d8

Let me know if I'm missing something here.
I will continue researching what could be happening.

**Comment by DamascenoRafael** [comment]
@od-gk got it, I'm happy it's working now, but please let me know if this issue happens again.
I'm going to close this issue for now, but if it happens again we can reopen it.
