### ISSUE TITLE
Maybe add the intelligent time and date addition like in reminders app.

### ISSUE THREAD

**Issue by gdavies3692** [DamascenoRafael/reminders-menubar#17]
<img width="265" alt="Screen Shot 2021-05-18 at 9 53 43 AM" src="https://user-images.githubusercontent.com/60199162/118673860-f65ea880-b7be-11eb-944d-e6e531526ebf.png">

**Comment by DamascenoRafael** [comment]
Hey, @gdavies3692!
I think it would be a great feature!  🚀   It's definitely on the roadmap!!

But I think it would depend on something like natural language date parser.
And it would also be interesting to think about support for different languages.

I think I would need some help for that.

**Comment by DamascenoRafael** [comment]
@gdavies3692 version 1.14.0 is now available. It is now possible to specify the due date with natural language 🔤 📅 

Please let me know if you have any feedback or suggestions for improvement.
