### ISSUE TITLE
Slovak localisation

### ISSUE THREAD

**Issue by Svec-Tomas** [DamascenoRafael/reminders-menubar#170]
Hi Rafael!

I am not very familiar with Github and Pull requests, but I do enjoy translating useful apps I use daily to my native language (Slovak). Please find attached the translated files.

I hope it is OK. If anything else is needed, just let me know.

Thanks!
[Reminders-Menubar.zip](https://github.com/DamascenoRafael/reminders-menubar/files/13854900/Reminders-Menubar.zip)

**Comment by Svec-Tomas** [comment]
Are the issues not looked after and checked? What should I do, to make this useful app available in my native language?

The instructions how to add a new language are very unclear to me. I am not even able to locate the Project Navigator mentioned in the first step :(

**Comment by DamascenoRafael** [comment]
@Svec-Tomas, thank you for your contribution!! 🎉 
I opened a PR with this change and Slovak localization will be available in the next release.

Some personal projects are taking a lot of time, so it's taking a while for me to look at the issues and respond. Sorry about that. I will review the instructions for adding localizations to be more detailed.
