### ISSUE TITLE
Allow start of the week from Monday (currently Sunday for me)

### ISSUE THREAD

**Issue by Svec-Tomas** [DamascenoRafael/reminders-menubar#175]
<img width="333" alt="Reminder" src="https://github.com/DamascenoRafael/reminders-menubar/assets/138758322/e43c6918-e882-410b-8779-0c4bdafa709d">

I am using Reminders Menubar in English and my beginning of the week is strangely starting from Sunday and not from Monday. Which is very strange, as I am located in Slovakia, Europe. Also the time is AM/PM, not our standard 24-hour format.

Is it possible to have start of the week from Monday and 24 hour time format, please?

Thanks!

**Comment by DamascenoRafael** [comment]
@Svec-Tomas, can you confirm if your preferred language in the app is "Use system language" or "English"?

**Comment by Svec-Tomas** [comment]
Please find attached the screen from my System Settings -> Language & Region

<img width="496" alt="Snímka obrazovky 2024-01-31 o 8 58 05" src="https://github.com/DamascenoRafael/reminders-menubar/assets/138758322/072f0bd6-1bff-4e06-a037-95b6e049a8b1">

**Comment by DamascenoRafael** [comment]
@Svec-Tomas Slovak was added as a supported language in version 1.22.0 (thanks for that!! 🎉 ), so I believe you will no longer experience this problem. But at the same time, in version 1.22.0 if you select "Use system language" the time formats must respect the system preferences if the language is not yet supported in the app.

**Comment by Svec-Tomas** [comment]
Hi Rafael, yes, this latest update including Slovak language fixed all issues for me. Thanks a lot!
