### ISSUE TITLE
App disappears when creating reminder with date

### ISSUE THREAD

**Issue by JeronimoMendes** [DamascenoRafael/reminders-menubar#176]
App disappears when creating a new reminder and using the date picker. I've tried creating a normal task and works fine.
Worth noting that the app process is still up and I need to kill it in order to restart.

**Machine**: Apple M1 Pro
**OS**: Sonoma 14.0 (23A344)

![ezgif-4-4fa321ba89](https://github.com/DamascenoRafael/reminders-menubar/assets/39437433/1de8bce9-f6a6-440d-9fbc-e03d7587dfe9)

**Comment by zydeico** [comment]
I can’t reproduce this issue, I try with dark/light mode on MacOS 15.0.1 

https://github.com/user-attachments/assets/3369fa10-939a-486e-9d27-cba65f95a016

**Comment by JeronimoMendes** [comment]
Hey @zydeico, I was running `v1.21` when I reported this issue. I just upgraded to `v1.23` and it seems the issue is fixed, and so I'm closing it.

Thanks for trying to work on it!
