### ISSUE TITLE
Transparent background request

### ISSUE THREAD

**Issue by artexhibit** [DamascenoRafael/reminders-menubar#2]
Hi Rafael! Nice app, really like it.

Have a little request, maybe you will consider to make it for future releases. 

Is it possible to make an app's background more transparent like all menu bar apps have?

I mean this effect: [PrintScreen](https://cln.sh/s1s1Yp)

**Comment by DamascenoRafael** [comment]
Hey, thanks for the suggestion.

It sounds interesting, I don't know if it should be the default, but maybe I could add an option in the menu to switch between more transparent or opaque. What do you think?

I'm not sure how transparency works in lists using SwiftUI, but there must be a way. 😄

**Comment by artexhibit** [comment]
> It sounds interesting, I don't know if it should be the default, but maybe I could add an option in the menu to switch between more transparent or opaque. What do you think?
Yes, the switcher will be welcomed! 😊

> I'm not sure how transparency works in lists using SwiftUI, but there must be a way. 😄
I am sure it is. Can't help you with advise on code side since I just only started to deal with SWIFT, but I am sure you will solve it.

**Comment by DamascenoRafael** [comment]
Hey @artexhibit, sorry for taking so long.

It turns out that the problem I had with SwiftUI with respect to the background did not affect the ability to make the background more transparent, which was great.

I tried it here and the result with transparency (0.3 opacity) was like this:

<img width="981" alt="Screen Shot 2021-02-13 at 17 36 05" src="https://user-images.githubusercontent.com/9842644/107861223-32324c80-6e23-11eb-8610-0146072551f3.png">

What do you think? I still want to improve the look of the text field in this scenario.

**Comment by artexhibit** [comment]
Hei, @DamascenoRafael 

It looks neat!

Agree with you about the text field. Maybe it will be better to make text fiend transparent as well and define the zone with a thin line (make it look like a thin rectangle)?

**Comment by DamascenoRafael** [comment]
I also thought about it at first, but I did some tests and it didn't look so nice (similar to the app's initial look).

I ended up choosing another color with some transparency for the text field background, I think it makes more sense with the overall look of the app, but we can improve over time.

<img width="816" alt="Screen Shot 2021-02-15 at 14 14 25" src="https://user-images.githubusercontent.com/9842644/107980112-772ebe00-6f9e-11eb-8dab-ff0c230c4d5b.png">

The menu option to change the look:

<img width="408" alt="Screen Shot 2021-02-15 at 15 07 12" src="https://user-images.githubusercontent.com/9842644/107980786-9e39bf80-6f9f-11eb-96be-118bf0f016d2.png">

**Comment by DamascenoRafael** [comment]
I will make a commit closing this issue, but we can continue to discuss how to improve the appearance of the app.

I'm going to release a new version these days with this feature already :)

**Comment by artexhibit** [comment]
> I will make a commit closing this issue, but we can continue to discuss how to improve the appearance of the app.
> 
> 
> 
> I'm going to release a new version these days with this feature already :)

Yeap. Looks stunning! One million dollars design! Wait to install!
