### ISSUE TITLE
Widget version

### ISSUE THREAD

**Issue by Angelk90** [DamascenoRafael/reminders-menubar#20]
Hi @DamascenoRafael , 

It would be very interesting to have also a widget style version, as a future feature.

![image](https://user-images.githubusercontent.com/20476002/125188725-15b10980-e235-11eb-91e5-4f9f9b00bb2c.png)

**Comment by DamascenoRafael** [comment]
I will try to find out how it is possible to interact through widgets.
I don't know if it would be possible to create reminders and interact with them directly through widgets. 
But if it is possible, it will definitely be something interesting.

**Comment by Angelk90** [comment]
@DamascenoRafael : Are there any news?

P.s.
Is there a way to contact you privately, I don't know twitter, facebook or email?

**Comment by DamascenoRafael** [comment]
Sorry, I didn't have time to study much about it.
Could it be through LinkedIn? On my GitHub there is a link to my LinkedIn page.

**Comment by Angelk90** [comment]
@DamascenoRafael : I would prefer not to have to use LinkedIn.

**Comment by DamascenoRafael** [comment]
@Angelk90 I'm not a big fan of twitter, but you can contact me there [@rafaeldamscn](https://twitter.com/rafaeldamscn)

**Comment by Angelk90** [comment]
@DamascenoRafael : I can not send messages on Twitter tells me are allowed.

**Comment by scottrobertson** [comment]
MacOS has a reminders widget built in. What benefit would it bring adding it here?

**Comment by DamascenoRafael** [comment]
Along with the evolution of this app, it became clear that there are different settings and a lot of possible features to work on. Trying to bring this to Widgets seems like a lot of effort (and contrary to some Apple guidelines). So in this scenario macOS already offers an ok widget option to view reminders and it seems to make more sense for this app to focus only on the menu bar (where macOS doesn't offer a solution). This may change in the future but seems more appropriate for the moment.
