### ISSUE TITLE
blank window in the menu bar

### ISSUE THREAD

**Issue by iskerwin** [DamascenoRafael/reminders-menubar#204]
In macOS beta 1, a blank window in the menu bar pops up every time you start your computer

**Comment by yunruse** [comment]
@iskerwin, do you mean macOS Sequoia (15) developer beta 1?

**Comment by iskerwin** [comment]
yes

**Comment by aayushbhatia06** [comment]
+1, same issue

**Comment by eplusg** [comment]
Same issue here, a blank "Reminders Menubar settings"-window shows up after rebooting.
Running Sequoia 15.0 Beta.

**Comment by kp7100** [comment]
same issue here! any workarounds?

**Comment by lint2015** [comment]
This also happens on the macOS 15.0 public release.

**Comment by DamascenoRafael** [comment]
New version will be released between September 18-19 with the fix.
Thank you all for reporting.

**Comment by DamascenoRafael** [comment]
Issue fixed in new version 1.23.0 now available.
