### ISSUE TITLE
App Crashes When Inputting Emoji

### ISSUE THREAD

**Issue by HuangxinDong** [DamascenoRafael/reminders-menubar#220]
Reminders-Menubar crashes whenever I try to input an emoji in it. I've tried reinstalling and updating the app, but the issue persists. Any assistance on how to resolve this would be greatly appreciated.

Steps to Reproduce:
1. Open Reminders-Menubar.
2. Create a new reminder.
3. Try to type or paste an emoji into the reminder text.
4. The app crashes immediately.

System Information:
- Device: MacBook Pro M2
- OS Version: macOS 14.5 
- Reminders-Menubar Version: v1.23.0

Crash Report:  
[CrashReport.txt](https://github.com/user-attachments/files/17201261/CrashReport.txt)

**Comment by zydeico** [comment]
Solved on PR #221

**Comment by DamascenoRafael** [comment]
@HuangxinDong, thanks for reporting this 👍 
I fixed this bug in a recent commit, fix will be in the next version which will be released soon.
