### ISSUE TITLE
Menubar arrow

### ISSUE THREAD

**Issue by Angelk90** [DamascenoRafael/reminders-menubar#23]
Hi @DamascenoRafael : 

As you can see from the images, whether it is opaque or transparent, light or dark, the part where the arrow is is always transparent.

I would recommend making sure that the color is the same as the content and there is no such transparency.

Opaque:
<img width="45" alt="Schermata 2021-08-04 alle 16 50 15" src="https://user-images.githubusercontent.com/20476002/128202795-9bd5bc10-e999-456e-ae45-5d86f8db4a02.png">
<img width="38" alt="Schermata 2021-08-04 alle 16 50 05" src="https://user-images.githubusercontent.com/20476002/128202799-d12894f5-5877-4ef7-bf7f-1b4cdae9be4c.png">

Transparent:
<img width="42" alt="Schermata 2021-08-04 alle 16 46 12" src="https://user-images.githubusercontent.com/20476002/128202170-e935d0be-e113-4c22-95fa-3e2304f30e49.png">
<img width="40" alt="Schermata 2021-08-04 alle 16 46 26" src="https://user-images.githubusercontent.com/20476002/128202166-68f3efc1-26e2-4cfa-8d03-4c29aae3bc34.png">

**Comment by DamascenoRafael** [comment]
@Angelk90 It's been a while, but I finally found a solution to this 🙌
