### ISSUE TITLE
App Does Not Request Security & Privacy Access to Reminders

### ISSUE THREAD

**Issue by aug0211** [DamascenoRafael/reminders-menubar#25]
It appears that Reminders Menu Bar is not requesting access to "Reminders" data from the "Security & Privacy" preference pane.

When I try to use the tool by clicking the icon in the menu bar, I receive and alert that access must be granted. However, Reminders Menu Bar does not appear in the Security and Privacy list of apps requesting access to Reminders data, for me to check the box and grant access.

This is on OS X 11.5.2 (Big Sur) and the latest version of Reminders Menu Bar v1.5.0.

Installation instructions were followed and the step to grant permission for an undefined developer was completed succesfully. Screen shots attached.

<img width="279" alt="Access not Enabled" src="https://user-images.githubusercontent.com/659845/132357040-d4b3f866-052e-4b6d-a27c-72f1303fd46e.png">
<img width="676" alt="Blank Security and Privacy" src="https://user-images.githubusercontent.com/659845/132357048-7095f6a7-04f7-4847-b11f-7326398186ac.png">

**Comment by DamascenoRafael** [comment]
Hey @aug0211, hadn't seen this problem yet.

The method that displays the screen requiring access to reminders is as follows:

```swift
private func requestAuthorization() {
    let authorization = RemindersService.instance.authorizationStatus()
    if authorization == .restricted || authorization == .denied {
        presentNoAuthorizationAlert()
    } else {
        RemindersService.instance.requestAccess()
    }
}
```

As you can see, the screen you are viewing is displayed when the authorization status is **restricted** or **denied**.

According to Apple's documentation:
- [denied](https://developer.apple.com/documentation/eventkit/ekauthorizationstatus/denied):
    The user explicitly denied access to the service for the app.
- [restricted](https://developer.apple.com/documentation/eventkit/ekauthorizationstatus/restricted)
    The user cannot change this app’s authorization status, possibly due to active restrictions such as parental controls being in place.

Any chance your user has some kind of restriction like this second case?

**Comment by aug0211** [comment]
Resolved!

This was an issue with my environment and not with Reminders Menu Bar.

I had SIP disabled on my machine and this had blocked the RMB prompt to gain access to reminders. Enabling SIP allowed the prompt to be displayed.

Thanks for taking a look and helping out!
________________________________

**Comment by DamascenoRafael** [comment]
Excellent!! Hope you enjoy the app 🚀 
Feel free to open any other issue
