### ISSUE TITLE
adopt sort order of lists from reminder app

### ISSUE THREAD

**Issue by hoobtron** [DamascenoRafael/reminders-menubar#28]
(right now lists are sorted alphabetically)

Additionally nice to have:
ability to change sorting of lists in the check-lists dropdown (left bottom button) by moving the title to another position

**Comment by DamascenoRafael** [comment]
Hey, @hoobtron. Thanks for the feedback and sorry for taking so long.
I will try to implement this for the next version! Let's keep the discussion on the oldest issue #21
