### ISSUE TITLE
Text field feedback

### ISSUE THREAD

**Issue by scottrobertson** [DamascenoRafael/reminders-menubar#3]
Hey

First of all, really like the app. Took me a while to find something like it. 

Just a few things about the text field at the top of the menu bar app. Could it be:

1) Made bigger (it feels kinda "un native" in a way).
2) Have the focus border removed
3) Have the text area the whole text field (without the padding around the text field inside it)

<img width="331" alt="Screenshot 2021-01-19 at 13 40 51@2x" src="https://user-images.githubusercontent.com/68361/105042631-5e44f280-5a5c-11eb-9a90-f59f63e86958.png">

And also, perhaps when i open the menu bar app, it auto focuses on the text field, so i can just start typing.

I guess like the Search in the Apple Reminders app:

<img width="281" alt="Screenshot 2021-01-19 at 15 35 16@2x" src="https://user-images.githubusercontent.com/68361/105056357-01e9cf00-5a6c-11eb-8d2b-a3476c816883.png">
<img width="279" alt="Screenshot 2021-01-19 at 15 35 21@2x" src="https://user-images.githubusercontent.com/68361/105056361-031afc00-5a6c-11eb-9c5b-f52193574e0c.png">

**Comment by DamascenoRafael** [comment]
Hey, I'm glad you liked it.

Thanks for the feedback! I hope we can find the best solutions.

1 - Do you say about the font size or the padding between the text and the surrounding area? Comparing to Apple Reminders it seems to me that the font is the same but the vertical padding should be higher. Perhaps points 2 and 3 will also help in this matter.

2 - Indeed, the current focus ring does not have an interesting look. One option would be to remove or try to make it look like the example you gave.

3 - Do you say about the focus ring? In Apple Reminders there is no overlap between the text and the icon. As stated in 2, we can place the focus ring on the outside (where there is already a border on the light theme) or simply remove the focus ring.

I liked the idea that when you open the app it automatically focuses on the text field. I think there is a workaround to change the focus using SwiftUI on macOS.

**Comment by DamascenoRafael** [comment]
Through your feedback I was thinking about a greater vertical padding, without the focus ring and some adjustments to the position of the text and icon. Like the image below:

<img width="930" alt="new-textfield" src="https://user-images.githubusercontent.com/9842644/105206142-cbbc5600-5b24-11eb-9e54-5a2c91e8fa30.png">

What do you think?

**Comment by scottrobertson** [comment]
> Through your feedback I was thinking about a greater vertical padding, without the focus ring and some adjustments to the position of the text and icon. Like the image below:
> 
> <img alt="new-textfield" width="930" src="https://user-images.githubusercontent.com/9842644/105206142-cbbc5600-5b24-11eb-9e54-5a2c91e8fa30.png">
> 
> What do you think?

Yes! That is so much better 👍

**Comment by DamascenoRafael** [comment]
I think you are right!

I also removed the dropdown border on the side.

Using the #EDEDED background this was the result:

<img width="400" alt="new-text-field-light-2" src="https://user-images.githubusercontent.com/9842644/105217020-18f2f480-5b32-11eb-9236-d62edc226221.png">

**Comment by scottrobertson** [comment]
Nice :) Looks much nicer without the border on the side too.

Do you think the dropdown should be the same height as the text field?

**Comment by DamascenoRafael** [comment]
I was trying a few different options. Which one looks nicer to you?

<img width="776" alt="textfield-dropdown-comparison3" src="https://user-images.githubusercontent.com/9842644/105224687-3e84fb80-5b3c-11eb-8849-2eaf95b5f70c.png">

**Comment by scottrobertson** [comment]
> I was trying a few different options. Which one looks nicer to you?
> 
> 
> 
> <img width="776" alt="textfield-dropdown-comparison3" src="https://user-images.githubusercontent.com/9842644/105224687-3e84fb80-5b3c-11eb-8849-2eaf95b5f70c.png">
> 
> 

Top right I think :)

**Comment by DamascenoRafael** [comment]
Agreed! 👍 

I will commit and close this issue then.

Can you open a new issue for the other idea you gave (when you open the app, it automatically focuses on the text field)? I think this part can be a little more complicated because of SwiftUI on macOS.

**Comment by scottrobertson** [comment]
Just built this locally. So much better! Thanks :)

**Comment by DamascenoRafael** [comment]
Great!! I will try to release a new version in the next few days with this change and other features 😄
