### ISSUE TITLE
Adding Shortcut / Hotkey support

### ISSUE THREAD

**Issue by Sevy007** [DamascenoRafael/reminders-menubar#32]
It would be great if the software would offer a hotkey support which acts similar to a mouse click on the icon in the menu bar. This saves switching to the mouse and back if the hands are already on the keyboard.

**Comment by adtemp1212** [comment]
Has this been done yet or no?

**Comment by DamascenoRafael** [comment]
This feature doesn't exist yet, but it looks like an interesting addition.
It would probably have to be a setting for the user to be able to change the shortcut they want to use.
I'd like a simple implementation within the app just for this purpose, but dealing with global shortcuts doesn't seem so simple. There are some libraries like [KeyboardShortcuts](https://github.com/sindresorhus/KeyboardShortcuts) that can make the job easier, but it still needs to be evaluated if it's worth adding as a dependency.

**Comment by philiplorenz-code** [comment]
Would be a gamechanger for my workflow! :)

**Comment by DamascenoRafael** [comment]
Planning to add in the next version.

What I've done so far:

Added the "Keyboard shortcut" option in the settings menu (showing the current shortcut if enabled).

Added a window that allows enabling and disabling the shortcut, as well as changing the key combination.

I'm thinking of leaving it disabled by default (to avoid possible conflict with other user shortcuts). For now I left the shortcut ⌥⌘R as a suggestion, but it can be changed by each user.

The behavior of the shortcut is to open the app in the menu bar if it is closed. If the app is already open, the shortcut is closing it.

Please let me know if you have any feedback.

<img width="571" alt="image" src="https://user-images.githubusercontent.com/9842644/190946026-37573286-69c7-41b0-9c0e-5b990829c609.png">

<img width="501" alt="image" src="https://user-images.githubusercontent.com/9842644/190946066-fd124818-ec36-4b5f-9c98-ece4ed07a4a3.png">
