### ISSUE TITLE
Cmd + A (Select All universal keyboard shortcut not working)

### ISSUE THREAD

**Issue by ChrisChiera** [DamascenoRafael/reminders-menubar#33]
When typing in the input box, tried press cmd + a to select all the text and doesn't work, just makes a beep. This works however in any other input on a Mac.

**Comment by DamascenoRafael** [comment]
That would be a great addition!
I think I found a way to add the main shortcuts to the text field: 
- select all (cmd + a)
- copy (cmd + c)
- paste (cmd + v)
- cut (cmd + x)
- undo (cmd + z)
- redo (cmd + shift + z).

I'm going to do some tests and if it works I should add this feature in the next release 👍
