### ISSUE TITLE
Remove/redesign colours in list filter

### ISSUE THREAD

**Issue by scottrobertson** [DamascenoRafael/reminders-menubar#37]
While it's nice to have the colours matching to the list, it is very hard to read some of them due to the background. For example "Family" is pretty hard to read.

![CleanShot 2021-11-06 at 13 17 59](https://user-images.githubusercontent.com/68361/140611107-faba686e-6662-43bc-b8b6-d1bade1682b4.png)

**Comment by DamascenoRafael** [comment]
@scottrobertson, I totally agree with you!

I was thinking of a way to still have the color without sacrificing readability.

How do you feel about adding a colored dot before the name of each list?

<img width="211" alt="Screen Shot 2022-03-02 at 18 21 02" src="https://user-images.githubusercontent.com/9842644/156452805-14cfa0cf-1052-432e-aef4-1bc0aaeb8c4e.png">

**Comment by scottrobertson** [comment]
> @scottrobertson, I totally agree with you!
> 
> 
> 
> I was thinking of a way to still have the color without sacrificing readability.
> 
> 
> 
> How do you feel about adding a colored dot before the name of each list?
> 
> 
> 
> <img width="211" alt="Screen Shot 2022-03-02 at 18 21 02" src="https://user-images.githubusercontent.com/9842644/156452805-14cfa0cf-1052-432e-aef4-1bc0aaeb8c4e.png">

I love it, as long as the assignment issue with ticked and unticked rows can be resolved 😃

**Comment by DamascenoRafael** [comment]
Great!! 🚀 

What do you mean by the assignment problem with ticked and unticked rows? Is it about issue #35 ?

**Comment by scottrobertson** [comment]
Alignment sorry. Stupid autocorrect.

**Comment by DamascenoRafael** [comment]
It happens, lol. But about which alignment are we talking?

In the screenshot I sent, the check icon appears aligned at the beginning (if the check icon doesn't exist, a blank space is left), then the colored dots are aligned with each other. The option of upcoming reminders turns out to be different.

Tell me about your idea and then we can try to change the interface a little more.

**Comment by scottrobertson** [comment]
> It happens, lol. But about which alignment are we talking?
> 
> 
> 
> In the screenshot I sent, the check icon appears aligned at the beginning (if the check icon doesn't exist, a blank space is left), then the colored dots are aligned with each other. The option of upcoming reminders turns out to be different.
> 
> 
> 
> Tell me about your idea and then we can try to change the interface a little more.

If you look at the red dot in comparison to the purple one under it you will see what i mean :)

**Comment by DamascenoRafael** [comment]
I hadn't noticed before 🤣 
I fixed the alignment of the colored dots.
The way I'm doing it with SwiftUI isn't the best, but other alternatives don't seem to work.

<img width="258" alt="Screen Shot 2022-03-05 at 19 05 48" src="https://user-images.githubusercontent.com/9842644/156901479-5bdc9f4e-f3af-47b8-816f-84374905b210.png">
