### ISSUE TITLE
How difficult would it be to compile a version for Catalina?

### ISSUE THREAD

**Issue by nik-field** [DamascenoRafael/reminders-menubar#40]
Wondering what are the constraining technologies/apis that require BigSur or later?

**Comment by treezyboost** [comment]
would like to know this as well.

**Comment by andylin2004** [comment]
I know that at the very least, the NSMenuBarItem icon will need to be replaced, as macOS Catalina doesn't support our current implementation of the SF Icon used. 

Idk about anything else

**Comment by DamascenoRafael** [comment]
Unfortunately the main reason for not supporting macOS Catalina is actually **SwiftUI** 😞 

The release of macOS Big Sur brought SwiftUI 2.0 (while macOS Catalina uses SwiftUI 1.0).

There were many changes from version 1.0 to 2.0 and many interface behaviors were changed, the Reminders Menu Bar that ran in Catalina when opening in Big Sur had a very different behavior and appearance.
