### ISSUE TITLE
Choose dark/light mode independent of system

### ISSUE THREAD

**Issue by milesmcclane** [DamascenoRafael/reminders-menubar#43]
Hello! 

Fab app. Thanks! Just what I was looking for. I wonder if it would be possible to be able to independently choose the mode? I work in dark mode predominantly, but I like certain types of apps (certainly menubar apps) to be displayed in light mode. I just find it easier to differentiate with what I’m otherwise doing like that. 

Thanks for the consideration! Of course, it doesn’t matter if it’s not a preference for you! More a little cosmetic adjustment. 

Cheers. 

Miles.

**Comment by DamascenoRafael** [comment]
@milesmcclane glad you liked the app!
I'm finishing working on this feature. Will be available in the next release 📦
