### ISSUE TITLE
Update strings related to renaming reminder in Localizable.strings

### ISSUE THREAD

**Issue by DamascenoRafael** [DamascenoRafael/reminders-menubar#45]
With the reminder rename feature some new strings were added.

I'm tagging here the people who have already helped with the translations.

@receyuki Chinese, Simplified
@Angelk90 Italian
@Somberland @4Ex4B German

Other contributors are welcome to help 👨‍💻 👩‍💻 
The strings that need to be translated are with the comment `// TODO: translate` at the end of the line.

**Comment by DamascenoRafael** [comment]
Thanks @Angelk90. Italian ✅

**Comment by receyuki** [comment]
#47 : )

**Comment by DamascenoRafael** [comment]
Thanks @receyuki! Chinese, Simplified ✅

**Comment by DamascenoRafael** [comment]
Still waiting for the German 🇩🇪  translations

https://github.com/DamascenoRafael/reminders-menubar/blob/58f2d0a6854f0ec47934bbfbb108077e9b772dba/reminders-menu-bar/Resources/de.lproj/Localizable.strings#L4-L8

**Comment by Somberland** [comment]
Somehow missed that ping :) -> https://github.com/DamascenoRafael/reminders-menubar/pull/49

**Comment by DamascenoRafael** [comment]
No problem @Somberland. Thanks for the PR :)

**Comment by DamascenoRafael** [comment]
Closing this issue since all translations for the *reminder rename* feature have been added 🌐
