### ISSUE TITLE
Pasting Text via Command-V does not work

### ISSUE THREAD

**Issue by bullitt186** [DamascenoRafael/reminders-menubar#48]
Preconditions:
- Mac OS Monterey 12.3.1
- Country Settings: Region Germany; Keyboard Layout German "Deutsch - Standard"
- Reminders 1.6.1 running
- have some Text in the clipboard

Steps:
- Open Reminders Menubar via Mouse
- Click into Entry Field
- Press Command-V to paste the text from the clipboard.

Expected Result:
- The text from the clipboard is pasted in the entry field

Observed Result:
- Nothing happens / no text is entered

Notes:
- It doesn't matter whether I have only one word or a long text in the clipboard. It does not matter how the text is formatted
- Rightklick into the text field and selecting "Einsetzen" (German for "Paste") from the rightclick-menu works as expected.

**Comment by DamascenoRafael** [comment]
Hey, @bullitt186.
Thanks for opening the issue.
Version 1.7.0 has already been released and should resolve this. 📦
The issue was addressed along with #33.
Let me know if you have any other problems.
