### ISSUE TITLE
"Add Task" button next to each list 

### ISSUE THREAD

**Issue by scottrobertson** [DamascenoRafael/reminders-menubar#5]
Instead (or as well as?) having the dropdown to select the task list you want to add a task to, it would be nice to be able to quickly just click next to each list. For example (using my amazing design skills):

![image](https://user-images.githubusercontent.com/68361/105047453-41132280-5a62-11eb-9609-2e6d37d7361a.png)

**Comment by DamascenoRafael** [comment]
That's a good idea 👏 

So clicking the plus button would change the list where the next reminder would be saved. It seems like a nice feature.

Do you think this should also save the reminder if something is already entered in the text field? - I don't know if it would seem like strange behavior or if it would make it easier to add new reminders.

**Comment by scottrobertson** [comment]
I was thinking it would just change the currently selected list at the top, but i guess it would save a click if it just saved right away if there was text in the field.

**Comment by DamascenoRafael** [comment]
Here is a video of how the feature looks. What do you think?

https://user-images.githubusercontent.com/9842644/105259819-44460580-5b6b-11eb-99a9-c1c4152f46ab.mp4

I was unsure about keeping the buttons always with the color of the calendar or just during the hover.

**Comment by scottrobertson** [comment]
While it makes sense in a way, I think it may be pretty confusing. I think maybe just have it change the list for now? Will probably have to be a different icon to a plus. Checkbox with an active state next to each list maybe?

**Comment by scottrobertson** [comment]
I had an idea. Could the button icon change if there is text in the text box?

So if not, have a circle/checkbox. If there is text, then show the Plus. May make it a lot clearer as to what is about to happen when you click.

**Comment by DamascenoRafael** [comment]
Nice! I'll try and send the result here.

**Comment by DamascenoRafael** [comment]
Here is a video of how it looks

https://user-images.githubusercontent.com/9842644/105439228-38c60d80-5c43-11eb-8cf2-6397aa0c4d2d.mp4

The icon changes whenever you start typing or when you save the reminder (since the text will be cleared), I don't know if it looks strange. I think maybe the ability to save directly with the click can be more confusing than helpful.

About the folder icon to select the list: I used the filled icon to indicate the list where the next reminder will be saved.

**Comment by scottrobertson** [comment]
Yeah I think you are correct, it's going to be confusing. I think just the switching logic for now. 

I guess really it should be an inline form like Reminders if we want to be able to add to a specific list right away. 

But being able to switch with a button is much faster than the drop down I think so I like it.

**Comment by DamascenoRafael** [comment]
Great! So I'm adding this logic to switch the calendar where the next reminder will be saved :)

Later, we can think about adding an inline form. I just saw how Apple Reminder does it.
