### ISSUE TITLE
Filter settings are constantly reset.

### ISSUE THREAD

**Issue by sohate** [DamascenoRafael/reminders-menubar#50]
Any action from my side and filter settings are reset. Can you fix it please? Latest MacOS, MacBook Air M1

**Comment by sohate** [comment]
I guess it's true. The only list is selected is "Upcoming Reminders" (the only list that I need). And when I do check any position all list select back.

What do I want: https://ibb.co/zrkHP56
What do I get when check any position: https://ibb.co/9NHp4Ph

**Comment by DamascenoRafael** [comment]
Closing this issue since it should be fixed in the latest version (1.7.1) 📦 
Let me know if you have any issues so we can investigate further.
