### ISSUE TITLE
Manual lists order

### ISSUE THREAD

**Issue by sohate** [DamascenoRafael/reminders-menubar#51]
Hello! Right now all my lists sort automatically by alphabet. Can I sort it manually? I want upcoming reminders be below filtered list.  Thanks!

https://ibb.co/64SW2MR

**Comment by DamascenoRafael** [comment]
Hey, @sohate. Thanks for the feedback.
Changing the order of the lists is something that has already been suggested, but that I haven't stopped to do yet.
Let's keep the discussion on the oldest issue #21. Please post any additional comments there.
I'm planning on adding this feature soon 👍
