### ISSUE TITLE
Update strings related to filtering reminder in Localizable.strings

### ISSUE THREAD

**Issue by DamascenoRafael** [DamascenoRafael/reminders-menubar#52]
With some changes to reminder filter options some new strings were added.

The strings that need to be translated are with the comment `// TODO: translate` at the end of the line:

🇨🇳  [zh-Hans.lproj/Localizable.strings#L16-L17](https://github.com/DamascenoRafael/reminders-menubar/blob/master/reminders-menu-bar/Resources/zh-Hans.lproj/Localizable.strings#L16-L17)
🇮🇹  [it.lproj/Localizable.strings#L16-L17](https://github.com/DamascenoRafael/reminders-menubar/blob/master/reminders-menu-bar/Resources/it.lproj/Localizable.strings#L16-L17)
🇩🇪  [de.lproj/Localizable.strings#L16-L17](https://github.com/DamascenoRafael/reminders-menubar/blob/master/reminders-menu-bar/Resources/de.lproj/Localizable.strings#L16-L17)

Sorry to bother you again, but I'm tagging here the people who have already helped with the translations ❤️ 

@receyuki Chinese, Simplified
@Angelk90 Italian
@Somberland @4Ex4B German

**Description about where these strings are used:**
When no filter is selected the app will show a message indicating that there are no reminders to display and asking the user to change the settings. Below is the example in English:

<img width="424" alt="Screen Shot 2022-06-12 at 02 27 47" src="https://user-images.githubusercontent.com/9842644/173217134-a71284c3-6d67-417e-9de5-483e97fa8c68.png">

Other contributors are welcome to help 👨‍💻 👩‍💻

**Comment by receyuki** [comment]
Done 👌
#54

**Comment by DamascenoRafael** [comment]
Thanks @receyuki and @Angelk90 

🇨🇳 Chinese, Simplified ✅ 
🇮🇹  Italian ✅

**Comment by Somberland** [comment]
https://github.com/DamascenoRafael/reminders-menubar/pull/55 👍

**Comment by DamascenoRafael** [comment]
Thanks @Somberland!

🇩🇪  German ✅

**Comment by DamascenoRafael** [comment]
Closing this issue since all translations for *reminder filter options* have been added 🌐
