### ISSUE TITLE
Does not open macOS 13 Beta 1

### ISSUE THREAD

**Issue by scottrobertson** [DamascenoRafael/reminders-menubar#56]
Nothing happens when I try and open the app. Nothing in menu bar, no crash etc. 

Anything I can do to help debug? Where can I check logs?

**Comment by DamascenoRafael** [comment]
Hey, @scottrobertson.
I'm not in the beta yet. Can you try compiling on the new Xcode 14?

**Comment by DamascenoRafael** [comment]
Hey, @scottrobertson. I ended up installing macOS Ventura beta and investigating the issue 🐞 
I will try to release a fix later this week ⚡ 

Unfortunately I don't have any docs. But anyway, to build just download the project and open the file `reminders-menu-bar.xcodeproj`. You may need to change the "Bundle Identifier" as below:

<img width="1156" alt="Screenshot 2022-06-28 at 01 47 21" src="https://user-images.githubusercontent.com/9842644/176095503-019a23af-d0db-4658-9dc8-c478e4f2fc89.png">

After that, when you click on the **play button** in the upper left corner, the project will be executed, to only build it is possible to use **cmd + b**.

**Comment by scottrobertson** [comment]
Working nicely now! Thanks for fixing.
