### ISSUE TITLE
Feature request: Indented reminders (i.e., sub-task's) support

### ISSUE THREAD

**Issue by abbott** [DamascenoRafael/reminders-menubar#58]
Hopefully, it's specified in Apple's API 🤞

**Comment by DamascenoRafael** [comment]
Sadly it still doesn't seem to be available on the Apple API.
I'm still checking to see if there is any news regarding this in the new macOS 13.

There is already an issue about this feature:
#36 Handle nested lists in filtering in a nicer way
I will close this issue and we can keep the discussion on issue #36.
