### ISSUE TITLE
New icon proposal

### ISSUE THREAD

**Issue by Zabriskije** [DamascenoRafael/reminders-menubar#59]
Hi folks,
I've kindly enjoyed Reminders Menu Bar, so here's a new app icon.
If you like it, feel free to use it.

[RemindersMenuBar.zip](https://github.com/DamascenoRafael/reminders-menubar/files/9389373/RemindersMenuBar.zip)

<img width="128" src="https://user-images.githubusercontent.com/101254295/185797209-7c6ad5c0-c90e-451f-a9e8-54b529d497ce.png">

**Comment by jkwroi24io9342fsdjklAdf** [comment]
I also think the menubar icon is not very good. 😁

**Comment by DamascenoRafael** [comment]
Hi @Zabriskije! Thanks for putting effort into it!! 👏 
Sorry for taking so long to give you feedback.

I'm definitely not a designer or UI developer, so my opinions are based solely as a user, hahaha.

The current app icon is a slight modification of the Apple Reminders icon, but there's no need to stick to that.

In general I'm not a big fan when the icon appears to be on top of a background. Although in this case the idea was to show the mac menu bar at the top. I'm not sure what your opinion is on this.

I like the idea of trying to show "a list" of reminders, but we can try to fit this into another format. I'm open to hear your ideas.

I've seen the other icons you've designed [on your page](https://macosicons.com/#/u/Zabriskije) and I love the results! 🚀

**Comment by Zabriskije** [comment]
Thanks for the appreciation 🫶

The first version it's more self-explanatory, but I understand that it takes away a bit of strength from the icon itself. Kind of a "tool" instead of an app.

Maybe just a more refined version of the current one? Like this:

<img width="128" src="https://user-images.githubusercontent.com/101254295/208076217-31a7c2d3-c626-4224-9c83-e8bb78a47058.png">
