### ISSUE TITLE
Request: Show due date/time, and if task is repeating

### ISSUE THREAD

**Issue by scottrobertson** [DamascenoRafael/reminders-menubar#6]
This is how Fantastical displays due date/time, along with an icon if the task is repeating or not.

<img width="150" alt="Screenshot 2021-01-20 at 17 55 12@2x" src="https://user-images.githubusercontent.com/68361/105215041-ae00e800-5b48-11eb-9284-c499ae79a69e.png">

**Comment by DamascenoRafael** [comment]
Nice! I'm looking at how to access this information and then we can discuss the best way to display it 👍

**Comment by scottrobertson** [comment]
Awesome. Should just be `reminder.dueDateComponents`

**Comment by DamascenoRafael** [comment]
That's right! 👍  
At the beginning I was thinking about showing the recurrence rules (like "daily", "every 2 days" etc). But it may be too much to accommodate on the screen.

Here are some possibilities:

<img width="1476" alt="reminders-due-date" src="https://user-images.githubusercontent.com/9842644/105610018-c280f280-5d8b-11eb-8e88-fbcca7dcb094.png">

What do you think? I don't know if you had something different in mind.

**Comment by scottrobertson** [comment]
Looks really awesome. 

How about the first one, but the recurring icon at the end of the date instead of start? Just to keep the date always in the same place. 

Also, if the due date is past, then I think the text should be red.

**Comment by DamascenoRafael** [comment]
Great. The red date when it's in the past is a nice touch, do you think the icon should be too?

<img width="799" alt="reminders-due-new-2" src="https://user-images.githubusercontent.com/9842644/105611648-3c69a980-5d95-11eb-9447-4c8614fc53da.png">

**Comment by scottrobertson** [comment]
Love it. And i think maybe the icon should stay the standard color.

**Comment by DamascenoRafael** [comment]
Perfect! I will make some improvements to the code and then finish this feature :)
