### ISSUE TITLE
Adding ShortCut option

### ISSUE THREAD

**Issue by philiplorenz-code** [DamascenoRafael/reminders-menubar#61]
Would be awesome to have a shortcut to display the app, so syou do not have to move your cursor to the status bar every time

**Comment by DamascenoRafael** [comment]
hey @philiplorenz-code, thanks for the feedback!!
It's something that's already on my radar.

Closing this issue as it is a duplicate of https://github.com/DamascenoRafael/reminders-menubar/issues/32 .
Let's keep the discussion on the original issue
