### ISSUE TITLE
Set date and time of reminder

### ISSUE THREAD

**Issue by zoulhh** [DamascenoRafael/reminders-menubar#64]
Hi,

is there a way to set a date and time for a reminder? Can't find it. Thank you.

Regards

Mick

**Comment by zoulhh** [comment]
Nobody else having this issue? I'm on macOS 13 Ventura.

**Comment by DamascenoRafael** [comment]
Hi @zoulhh, thanks for the feedback! 

Currently it is not possible to add or edit date/time through the App.

The App already displays the date/time that are set by Apple Reminders.
So it is expected that it will be possible to set it through the App as well.

This feature is clearly on my roadmap.

**Comment by jmuheim** [comment]
I'd definitely love to see this feature. 🚀

**Comment by quetzal-98** [comment]
Being able to set a due date when adding a new reminder would really be beneficial. Same for tagging ;)

**Comment by andylin2004** [comment]
I made PR #80 for this

**Comment by DamascenoRafael** [comment]
@zoulhh @jmuheim @quetzal-98 this feature is now available in the new **version 1.11.0** 📦 🚀 
Any new feedback is very welcome :)

Thank you @andylin2004 for helping me make this feature available.

@quetzal-98 tagging still doesn't seem to be possible with the Apple APIs.
There is already a dedicated issue for this: https://github.com/DamascenoRafael/reminders-menubar/issues/83
