### ISSUE TITLE
Update strings related to keyboard shortcuts in Localizable.strings

### ISSUE THREAD

**Issue by DamascenoRafael** [DamascenoRafael/reminders-menubar#66]
With the addition of the keyboard shortcut feature some new strings were added.

The strings that need to be translated are with the comment `// TODO: translate` at the end of the line:

🇨🇳 Chinese (Simplified): [zh-Hans.lproj/Localizable.strings](https://github.com/DamascenoRafael/reminders-menubar/blob/master/reminders-menu-bar/Resources/zh-Hans.lproj/Localizable.strings#L29;L41)
🇳🇱 Dutch: [nl.lproj/Localizable.strings](https://github.com/DamascenoRafael/reminders-menubar/blob/master/reminders-menu-bar/Resources/nl.lproj/Localizable.strings#L29;L41)
🇩🇪 German: [de.lproj/Localizable.strings](https://github.com/DamascenoRafael/reminders-menubar/blob/master/reminders-menu-bar/Resources/de.lproj/Localizable.strings#L29;L41)
🇮🇹 Italian: [it.lproj/Localizable.strings](https://github.com/DamascenoRafael/reminders-menubar/blob/master/reminders-menu-bar/Resources/it.lproj/Localizable.strings#L29;L41)
🇲🇽 Spanish (Latin America): [es-419.lproj/Localizable.strings](https://github.com/DamascenoRafael/reminders-menubar/blob/master/reminders-menu-bar/Resources/es-419.lproj/Localizable.strings#L29;L41)

Sorry to bother, but I'm tagging here the people who have already helped with the translations ❤️

@receyuki Chinese (Simplified)
@wdg Dutch
@Somberland @4Ex4B German
@Angelk90 Italian
@zydeico  Spanish (Latin America)

Other contributors are welcome to help 👨‍💻 👩‍💻

**Description about where these strings are used:**

There is a new option in the settings menu and also a new window to change keyboard shortcut options.

<img width="550" alt="Screenshot 2022-09-24 at 21 15 08" src="https://user-images.githubusercontent.com/9842644/192123029-96f61aa8-fd6f-4e6a-bc7d-5b2075194f09.png">

<img width="565" alt="Screenshot 2022-09-24 at 21 15 21" src="https://user-images.githubusercontent.com/9842644/192123028-3faad2c2-d988-4340-987f-57ce7c5bb696.png">

**Comment by wdg** [comment]
I will add the translations tonight (local time). 😊

**Comment by DamascenoRafael** [comment]
Thanks to everyone for the contributions 🎉 

Just need the translation to 🇲🇽 Spanish (Latin America).
@zydeico do you think you can give a quick help with this? :)

https://github.com/DamascenoRafael/reminders-menubar/blob/5e18be7a9456b4ad2b1392ceb211d871edc0541f/reminders-menu-bar/Resources/es-419.lproj/Localizable.strings#L29-L41

**Comment by zydeico** [comment]
Yeah! Working in that

**Comment by zydeico** [comment]
@DamascenoRafael is done in the PR #73 😄

**Comment by zydeico** [comment]
> Thanks to everyone for the contributions 🎉
> 
> Just need the translation to 🇲🇽 Spanish (Latin America). @zydeico do you think you can give a quick help with this? :)
> 
> https://github.com/DamascenoRafael/reminders-menubar/blob/5e18be7a9456b4ad2b1392ceb211d871edc0541f/reminders-menu-bar/Resources/es-419.lproj/Localizable.strings#L29-L41

@DamascenoRafael it's done in the PR #73 😄

**Comment by DamascenoRafael** [comment]
Thanks to everyone for the contributions 🎉

In the text for `keyboardShortcutEnableOpenShortcutOption` the name of the app ("_Reminders Menu Bar_") did not need to be translated. Sorry for not paying attention to this detail during the PR review.

I changed the original text to contain a parameter (which will be automatically replaced by the app name).
New original text: "_Enable keyboard shortcut to open %@_"


@receyuki, @wdg, @Somberland, @Angelk90 can you make this small update in the translation?

**Comment by DamascenoRafael** [comment]
All done! 🎉 
Next release will contain these translations 🚀
