### ISSUE TITLE
Add #Hacktoberfest and Hacktoberfest-accepted to gain more attention for this project

### ISSUE THREAD

**Issue by 0xWDG** [DamascenoRafael/reminders-menubar#78]
Add #Hacktoberfest and Hacktoberfest-accepted to gain more attention for this project

**Comment by DamascenoRafael** [comment]
Thanks a lot for the suggestion @0xWDG. October has already passed, but I want to organize the repository issues, including creating some new ones about features that I think would be interesting, and detailing them. This might make it easier to encourage new contributions.
