### ISSUE TITLE
Feature Request: support Today list

### ISSUE THREAD

**Issue by Reiji777** [DamascenoRafael/reminders-menubar#93]
First of all, many thanks for this great app!

In the native Reminder app on iOS/MacOS, there's a Today list that shows all the items due today. If you add an item in the list, the item is **automatically** scheduled to be due today as well. I was wondering if such list can be supported?

**Comment by DamascenoRafael** [comment]
Hey @Reiji777! I'm glad that you are enjoying the app :)

Currently the app can show a list of reminders with a due date (either for today, in a week or in a month). You were able to find this option, right?

<img width="681" alt="Screenshot 2023-01-02 at 19 42 27" src="https://user-images.githubusercontent.com/9842644/210282808-eb710a45-2c18-4227-9914-125f6eda7c9b.png">

From what I understand you would like to add an item directly to that list (in fact the native app creates the reminder in another list, but with the due date for today).

What would be possible today would be when typing the new reminder click on "Add Date" as this would add a due date for today.

<img width="645" alt="Screenshot 2023-01-02 at 19 51 10" src="https://user-images.githubusercontent.com/9842644/210283056-92806350-d4d1-47ea-84d0-10e2049b24c2.png">

Let me know if I understand correctly. We can try to evaluate how to improve this experience.

**Comment by Reiji777** [comment]
Hey @DamascenoRafael Thanks for the response!  You got my original inquiry correctly, and I'm aware of the functionalities you mentioned. Was just wondering if there's a way to automatically set the due date as today, instead of having to click on "Add Date". This is probably pretty trivial as it only saves one or two clicks :)

Btw, I was able to create a shortcut to achieve so in the Shortcut app.

**Comment by DamascenoRafael** [comment]
@Reiji777 now in version 1.14.0 there is an option so that when typing a new reminder the date is auto-suggested as today:

<img width="742" alt="221477562-4267ebb3-90c2-4750-a297-2f2bfd28b6b8" src="https://user-images.githubusercontent.com/9842644/221741195-07d19729-9425-49ab-a3ba-93d6970813e9.png">

Please let me know if you have any feedback or suggestions for improvement.
