### ISSUE TITLE
Subtasks

### ISSUE THREAD

**Issue by CyberWho** [DamascenoRafael/reminders-menubar#94]
Hey! I just installed the app and one feature that I find is really missing is the support for subtasks. If I haven't missed something, there is no task nesting, as there is in the Reminders app (but please correct me if I am wrong).

I am unfortunately not a Swift developer, so I cannot help you implement it :/

**Comment by DamascenoRafael** [comment]
Hi @CyberWho, thanks for your feedback!
Yes, you are correct, currently the app does not display the subtasks/nested-lists/reminder-group format.

As this app relies on **Apple API** to access reminders, there are some limitations as Apple does not allow access to some properties of reminders. Unfortunately, I don't know the reason for not allowing access to subtask information in particular.

There are some workarounds for situations like this and I'm trying to figure out how this can be implemented for the app.

There is already an older issue about this feature, we can keep the discussion there: https://github.com/DamascenoRafael/reminders-menubar/issues/36 [Handle nested lists (subtasks) in filtering in a nicer way ](https://github.com/DamascenoRafael/reminders-menubar/issues/36).
