### ISSUE TITLE
Not appearing on menu bar

### ISSUE THREAD

**Issue by petersonsim** [DamascenoRafael/reminders-menubar#96]
Hello,

Unsure of what's causing the issue, but I cannot get reminders to even appear on the menu bar. Everything is all up-to-date, so I'm not sure what else could be obstructing the app from opening.
<img width="1512" alt="Screenshot 2023-01-04 at 07 50 50 PM" src="https://user-images.githubusercontent.com/105251221/210699361-757346a6-2fb4-4f61-9012-23d481ff67c8.png">

**Comment by DamascenoRafael** [comment]
Hello @petersonsim, thanks for reporting this.

When you try to open the app do you get any messages/alerts?
You can open the app through Launchpad (second dock icon) or you can open it through Spotlight.

**Comment by petersonsim** [comment]
Thanks for looking into this! I'm not getting any messages when I open the app via the routes you mentioned.

![Screenshot 2023-01-04 at 08 29 39 PM](https://user-images.githubusercontent.com/105251221/210702503-e30876ad-5ab3-459a-897a-b68d83a56a80.gif)

![Screenshot 2023-01-04 at 08 32 32 PM](https://user-images.githubusercontent.com/105251221/210702518-4999150b-be9c-4a08-858f-869b67a12f28.gif)

The only message that popped up was upon initial installation (Reinstalled to show what I was seeing):

![Screenshot 2023-01-04 at 08 41 11 PM](https://user-images.githubusercontent.com/105251221/210703507-40564b5d-5c69-41c1-8bc4-40899f3d2ee3.gif)

**Comment by numbcoder** [comment]
I had the same issue.
Open the app from Launchpad, but nothing happened.
Environment: macOS 13.1, Reminders Menu Bar 1.12.0

**Comment by DamascenoRafael** [comment]
Can you please open Activity Monitor to see if the "Reminders Menu Bar" process is running? Just to know if the app is running and not showing up or if it's not running at all.

**Comment by DamascenoRafael** [comment]
Also, I'm not sure if it could be related to #95. Can you please update to v1.12.1 and check if the problem persists?

**Comment by petersonsim** [comment]
> Also, I'm not sure if it could be related to #95. Can you please update to v1.12.1 and check if the problem persists?

Updating to v1.12.1 did the trick for me! Thanks for the support!

**Comment by DamascenoRafael** [comment]
Great to hear it @petersonsim! :)
I'll keep the issue open until I get a response from @numbcoder as he was also having the problem.

@numbcoder can you please check if v1.12.1 solved your problem?

**Comment by numbcoder** [comment]
Yes, it works perfectly now! Thanks for your quick response!

**Comment by DamascenoRafael** [comment]
Awesome!! I'm happy it's working.
