### ISSUE TITLE
No reminder notification when date time set in menubar

### ISSUE THREAD

**Issue by simonstlzl** [DamascenoRafael/reminders-menubar#98]
Just started using the menubar. I noticed that I don't get reminder notifications when I set the date time in the menubar. Could you please help me here? Thank you!

**Comment by DamascenoRafael** [comment]
Hey @simonstlzl, thanks for reporting this.

Can you give me some more information about that?
Was the reminder you created from the menu bar for the whole day or a specific time?
Opening Apple Reminders does the reminder appear correctly with the due date configured?

I think I know why this could be happening. Might be related to this commit: https://github.com/DamascenoRafael/reminders-menubar/commit/41542aefe411dca6df5241c9e2b08160503e795f.

I can revert it, but before this commit when a reminder was created for the whole day it made it appear with a time set to the beginning of the day (00:00). So I need to find a way to solve this first.

I'll try to reproduce the issue on my side, and test some solution. I'll let you know as soon as I have an update on that.

**Comment by simonstlzl** [comment]
Thanks for the response.

No, the reminder is for a specific date and time. Opening the Apple Reminders app the reminder does appear correctly. However, I don't get a notification on any of my devices. When I set a date and time in the Reminders app, I do get a notification across all my devices.

Hope this helps to reproduce this issue.

**Comment by DamascenoRafael** [comment]
@simonstlzl I believe I fixed this in version 1.13.0. 📦  
But the fix won't affect reminders that had date/time previously set via the menu bar (only if the reminder has the date/time changed again by the menu bar in version 1.13.0).

Can you please test and let me know if it's working as if the date/time was set by Apple Reminders?
